name: Build
'on':
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and analyze
        env:
          GITHUB_TOKEN: 782bcf9f-315e-4e91-9050-ab0e5da14a88
          SONAR_TOKEN: e62c84adbcfda79e46a9c096fbf892c15140994b
        run: >-
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=examly-test_782bcf9f-315e-4e91-9050-ab0e5da14a88
          -Dsonar.login=e62c84adbcfda79e46a9c096fbf892c15140994b
